### PR TITLE
Update dep npm module names

### PR DESCRIPTION
**Pull request by kenny-y**

### CODE REVIEW

**Comment by huningxin** [comment]
Probably, we can update the "npm install" steps in README.md of each sample.

**Comment by kenny-y** [comment]
> we can update the "npm install" steps in README.md of each sample.

Sorry I didn't quite get that... what would be your preference on the solution to this issue?

**Comment by huningxin** [comment]
I mean to remove the "Not Ready" for npm steps like https://github.com/huningxin/realsense_samples/blob/javascript-dev/samples/or_tutorial_1/javascript/README.md#from-npm-not-ready

**Comment by kenny-y** [comment]
Roger that. I did forget the `README` part...

**Comment by huningxin** [comment]
I can deal with the README.md. Merging...

**Pull request merged**
